#!/bin/sh
#
# skeleton	Example initscript
#		This file should be used to construct scripts to be
#		placed in /etc/init.d.
#
# Author:	Andrew Holt
#
#
# set -e

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DESC="spread messaging server."
NAME=spread
DAEMON=/usr/local/sbin/spread
PIDFILE=/var/run/$NAME.pid
SCRIPTNAME=/etc/init.d/$NAME
CFG=/usr/local/etc/spread.conf

# Gracefully exit if the package has been removed.
test -x $DAEMON || exit 0


# Read config file if it is present.
#if [ -r /etc/default/$NAME ]
#then
#	. /etc/default/$NAME
#fi
#
#
#	Function that starts the daemon/service.
#
d_start() {
	HOST=`hostname`
#    HOST="macbook"
#    HOST=localhost

    if [ ! -d /var/run/spread ]; then
        mkdir -p /var/run/spread
    fi

    $DAEMON -n $HOST -c $CFG > /dev/null &
    echo $! > $PIDFILE
}
#
#	Function that stops the daemon/service.
#
d_stop() {
	echo "Stop"
    kill `cat $PIDFILE`
    rm $PIDFILE
}

#
#	Function that sends a SIGHUP to the daemon/service.
#
d_reload() {
	start-stop-daemon --stop --quiet --pidfile $PIDFILE \
		--name $NAME --signal 1
}

case "$1" in
  start)
	echo "Starting $DESC: $NAME"
	d_start
	echo "."
	;;
  stop)
	echo "Stopping $DESC: $NAME"
	d_stop
	echo "."
	;;
  #reload)
	#
	#	If the daemon can reload its configuration without
	#	restarting (for example, when it is sent a SIGHUP),
	#	then implement that here.
	#
	#	If the daemon responds to changes in its config file
	#	directly anyway, make this an "exit 0".
	#
	# echo -n "Reloading $DESC configuration..."
	# d_reload
	# echo "done."
  #;;
  restart|force-reload)
	#
	#	If the "reload" option is implemented, move the "force-reload"
	#	option to the "reload" entry above. If not, "force-reload" is
	#	just the same as "restart".
	#
	echo -n "Restarting $DESC: $NAME"
	d_stop
	sleep 1
	d_start
	echo "."
	;;
  *)
	# echo "Usage: $SCRIPTNAME {start|stop|restart|reload|force-reload}" >&2
	echo "Usage: $SCRIPTNAME {start|stop|restart|force-reload}" >&2
	exit 1
	;;
esac

exit 0
